Update lifecycle event and callback documentation
laravel-doctrine/docs pull request #70
Opened 2017-06-29 14:57 UTC by FoxxMD

* Clarify the difference between events and callbacks
* Add the listener() method for builder added by laravel-doctrine/fluent#45

2017-06-29 14:59 UTC, FoxxMD commented
@patrickbrouwers I can make PRs for the other branches if you want. Just let me know!

2017-06-29 15:16 UTC, guiwoda commented on fluent/reference.md
> +**Lifecycle Event** Listeners and Subscribers are classes with specific callback methods that receives some kind of EventArgs instance.
@FoxxMD can we look for an alternative to the "some kind of" phrase?

> Both Listener and Subscriber classes can hook into **Lifecycle Events**. The event dispatcher will then call on the specific callback method with a specific instance of `EventArgs`, depending on the event type.

2017-06-29 15:16 UTC, guiwoda commented on fluent/reference.md
> +**Lifecycle Callbacks** are methods on the entity classes that are called when the event is triggered.
@FoxxMD if you change phrasing as suggested above, maybe this one could change as well:

> Entities themselves can listen to **Lifecycle Callbacks** and have a method called on them when a specific event is triggered.

2017-06-29 18:38 UTC, FoxxMD commented
@guiwoda I added more info on EventArgs and also simplified the section. I made a clarification on the first section as really its about "listeners for Lifecycle Events" rather than "Lifecycle Event triggered by Lifecycle Event" which is kind of how it read previously. Let me know what you think.

2017-06-29 18:48 UTC, patrickbrouwers requested changes

2017-06-29 18:48 UTC, patrickbrouwers commented on fluent/reference.md
Perhaps good to update the index at the top of the page too. Not still refers to the callbacks only.

2017-06-29 19:02 UTC, guiwoda requested changes
A lot better! Just a small typo I found

2017-06-29 19:02 UTC, guiwoda commented on fluent/reference.md
> +_Lifecycle Callbacks_ can be triggered for a **subset** of _Lifecycle Events_. A callback is defined on an Entity class and are triggered when an instance of that Entity experiences a relevant Event.
(...) and _is_ triggered when an (...)

2017-06-29 20:13 UTC, FoxxMD reviewed
Minor changes

2017-06-29 20:13 UTC, FoxxMD commented on fluent/reference.md
This occurred to me too but I wanted to leave intact in case someone has this exact URL bookmarked. Very small chance I guess :)

2017-06-29 20:13 UTC, FoxxMD commented on fluent/reference.md
> +_Lifecycle Callbacks_ can be triggered for a **subset** of _Lifecycle Events_. A callback is defined on an Entity class and are triggered when an instance of that Entity experiences a relevant Event.
fixed, good find.

2017-06-29 20:14 UTC, FoxxMD commented
I don't totally understand how reviews were but I pushed both changes 👍

2017-07-02 06:49 UTC, patrickbrouwers approved these changes

2017-07-02 06:49 UTC, merged